# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c92319c5cb41d57944d2d119dcfd918bd3f2307bd231e1b22a468b4f529a1346599db945b0772cd2e68e8e9ff6a5950cf409d764de8b3807b5df706195f7d7fe

test:
  secret_key_base: 06bc9ab0754947c54970e47b2c0927094aaa81c208099eaede6d6a03b5b75854293cbaff6057ea6cdf766724694673dc104db947ad410b0084f9b0a89dd690c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
